// Generated by CoffeeScript 1.7.1
(function() {
  var App, global, riot;

  if (typeof window !== "undefined" && window !== null) {
    global = window;
    if (typeof riot === "undefined" || riot === null) {
      throw "riot not defined";
    }
  } else {
    global = exports;
    riot = require("riotjs");
  }

  App = function(conf) {
    var self;
    self = riot.observable(this);
    $.extend(self, conf);
    return setTimeout(function() {
      return self.trigger("ready");
    }, 1);
  };

  global.app = riot.observable(function(arg) {
    var instance;
    if (!arg) {
      return instance;
    }
    if ($.isFunction(arg)) {
      return app.on("ready", arg);
    } else {
      instance = new App(arg);
      return instance.on("ready", function() {
        return app.trigger("ready", instance);
      });
    }
  });

}).call(this);

//# sourceMappingURL=app.map
